shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('<int:creator_id>/', views.creator_product_list, name='product_list'),
    path('<int:creator_id>/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

slimeRoad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Creator(AbstractUser):
    bio = models.TextField()
    image = models.ImageField(upload_to='creator/%Y/%m/%d')

orders/models.py
from django.db import models

from shop.models import Product


class Order(models.Model):
    product = models.ForeignKey(
        Product,
        null=True,
        related_name='orders',
        on_delete=models.SET_NULL
    )
    email = models.EmailField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return self.email

shop/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Product(models.Model):
    creator = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='products'
    )
    name = models.CharField(max_length=200)
    description = models.TextField()
    link = models.URLField()
    slug = models.SlugField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

orders/forms.py
from django import forms

from .models import Order


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['email', 'price',]

orders/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from accounts.models import Creator
from orders.forms import OrderCreateForm

from .models import Product


def creator_product_list(request, creator_id):
    creator = Creator.objects.get(id=creator_id)
    products = Product.objects.filter(creator=creator)

    return render(request, 'shop/product/list.html', locals())


def product_detail(request, id, slug, creator_id):
    creator = Creator.objects.get(id=creator_id)
    product = get_object_or_404(Product, id=id, slug=slug)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST) 

        if form.is_valid():
            order = form.save(commit=False)
            order.product = product
            order.paid = False

            payment_price = order.price
            product_price = product.price

            if product_price == 0.00:
                    form.save()
                    messages.success(request, f'${payment_price} payment accepted')
                    # return redirect(reverse('payment:process'))
            elif payment_price >= product_price:
                    form.save()
                    messages.success(request, f'${payment_price} payment accepted')
                    # return redirect(reverse('payment:process'))
            else:
                messages.error(request, f'${payment_price} lower than product\'s price ${product_price}')
    else:
        form = OrderCreateForm()

    return render(request, 'shop/product/detail.html', locals())

shop/templates/main.html
{% load static %}
<!DOCTYPE html>

<html lang="en" class="no-js" >
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Slime Road {% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

{% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert-box alert-box--{{message.tags}}">
            <p>{{message|safe }}</p>
            <span class="alert-box__close"></span>
        </div>
        {% endfor %}
    </div>
{% endif %}


{% block content %}
{% endblock %}

</body>
</html>

shop/templates/shop/product/detail.html
{% extends 'main.html' %}


{% block content %}
<h1>{{ creator.username }}</h1>


<h3>{{ product.name }}</h3>
<h4>${{ product.price }}</h4>
<p>
    {{ product.description }}
</p>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Purchase">
</form>

{% endblock %}

shop/templates/shop/product/list.html
{% extends 'main.html' %}

{% block content %}

<h1>{{ creator.username }}</h1>

{% for product in products %}
    <h3><a href="{% url 'shop:product_detail' creator.id product.id product.slug %}">{{ product.name }}</a></h3>
    <h4>${{ product.price }}</h4>
{% endfor %}

{% endblock %}